YoRHa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("bunker.urls")),
]

bunker/urls.py
from django.urls import include, path
from . import views as bunker_views

from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path("", bunker_views.bunker_startingpage, name="bunker_startingpage"),
    path("contact_log/", include("contact_log.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact_log/urls.py
from django.urls import path

from . import views as contact_log_views

app_name = "contact_log"

urlpatterns = [
    path('<int:contact_id>/', contact_log_views.contact, name='contact'), 
    path("search/", contact_log_views.contact_log_search, name="search"),
    path("", contact_log_views.contact_log_startingpage, name="contact_log_startingpage"),
    ]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bunker/models.py
from django.db import models

# Create your models here.

contact_log/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Rank(models.Model):
    class Meta:
        verbose_name = "Rank"
        verbose_name_plural = "Ranks"
    
    name = models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return f'{self.name}'

class Contact(models.Model):
    name = models.CharField(max_length=50)
    rank = models.ForeignKey(
        Rank,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    picture = models.ImageField(blank=True, upload_to="pictures/contact_log/")
    creating_user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    
    
    # def __str__(self) -> str:
    #     if self.last_name == "":
    #         return f"{self.name}, {self.position}"
    #     return f"{self.name} {self.last_name}, {self.position}"
# Create your models here.

bunker/views.py
from django.shortcuts import render

def bunker_startingpage(request):
    return render(request, 'bunker/homepage.html')
# Create your views here.

contact_log/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from django.core.paginator import Paginator
from contact_log.models import Contact

def contact_log_startingpage(request):
    
    contacts = Contact.objects.all().order_by("id")
    paginator = Paginator(contacts, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        "page_obj" : page_obj,
        "site_title": "Contacts",
    }
    
    return render(request, 'contact_log/homepage.html', context)

def contact_log_search(request):
    
    search_value = request.GET.get("q", "").strip()
    
    if search_value == "":
        return redirect("contact_log:contact_log_startingpage")
    
    contacts = Contact.objects\
            .filter(
            Q(name__icontains=search_value) |
            Q(rank__name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
        )\
        .order_by("id")
        
    paginator = Paginator(contacts, 6)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
        
    context = {
        "page_obj" : page_obj,
        "site_title": "Contacts",
        'search_value': search_value,
    }
    
    return render(request, 'contact_log/homepage.html', context)

def contact(request, contact_id):
    single_contact = get_object_or_404(
        Contact, pk=contact_id
    )

    context = {
        'contact': single_contact,
        "site_title": single_contact.name
    }

    return render(
        request,
        'contact_log/single_contact.html',
        context
    )
# Create your views here.

bunker/templates/bunker/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bunker/css/homepage.css' %}">
    <title>YoRHa Bunker</title>
</head>
<body>
    <a href="http://127.0.0.1:8000/contact_log/" style="text-decoration: none; 
    padding: 10px 20px; background-color: white; color: darkgreen; border-radius: 5px; 
    font-weight: bold; display: inline-block;">Contact Log</a>
    <a href="http://127.0.0.1:8000/admin/" style="text-decoration: none; 
    padding: 10px 20px; background-color: white; color: darkgreen; border-radius: 5px; 
    font-weight: bold; display: inline-block;">Admin Console</a>
</body>
</html>

contact_log/templates/contact_log/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<body>

    {% include "contact_log/partials/_header.html" %}

    {% if page_obj %}

        <nav class="menu">
            <ul class="menu-list">
            <li class="menu-item">
                <a href="" class="menu-link">
                Link 1
                </a>
            </li>
            <li class="menu-item">
                <a href="" class="menu-link">
                Link 2
                </a>
            </li>
        </ul>
        </nav>
    
        <div class="search">
            <form 
            action=" {% url "contact_log:search" %} " 
            method="GET"
            >
            <input 
                type="search" 
                class="search-input"
                placeholder="Search"
                id="search"
                name="q"
            >
            </form>
        </div>
        </header>

    {% block content %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption ">
                Contacts
            </caption>

        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">Name</th>
                <th class="table-header">Rank</th>
                <th class="table-header">Phone</th>
                <th class="table-header">E-mail</th>
            </tr>
        </thead>

        <tbody>
            {% for contact in page_obj %}
                <tr class="table-row">
                    <td class="table-cel">
                        <a class="table-link"
                        href="{% url 'contact_log:contact' contact.id %}"
                        >

                            {{ contact.id }}
                        </a>
                </td>
                <td class="table-cel">
                    {{ contact.name }}
                </td>
                <td class="table-cel">
                    {{ contact.rank }}
                </td>
                <td class="table-cel">
                    {{ contact.phone }}
                </td>
                <td class="table-cel">
                    {{ contact.email }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "contact_log/partials/_pagination.html" %}
</div>

{% endblock content %}

    {% else %}
    <div class="single-contact">
        <h1 class="single-contact-name">
        No file found.
        </h1>
    </div>
{% endif %}
</body>
</html>

contact_log/templates/contact_log/partials/_header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'contact_log/css/homepage.css' %}">
    <title>{{ site_title}} - Contact Log</title>
</head>

<header class="header">
    <h1 class="header-heading">
    <a 
    href="{% url 'contact_log:contact_log_startingpage' %}" class="header-link">
    Contact Log
    </a>
    </h1>
</header>

contact_log/templates/contact_log/partials/_pagination.html
{% if page_obj %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&q={{ request.GET.q.strip }}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q.strip }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q.strip }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&q={{ request.GET.q.strip }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

contact_log/templates/contact_log/single_contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<body>

    {% include "contact_log/partials/_header.html" %}
    
    {% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
        {{ contact.name }} <br>
        {{ contact.rank }}
        </h1>

        <p><b>ID:</b> {{ contact.id }}</p>
        <p><b>E-mail:</b> {{ contact.email }}</p>
        <p><b>Phone:</b> {{ contact.phone }}</p>
        <p><b>Created Date:</b> {{ contact.created_date }}</p>
        <p><b>Description:</b> {{ contact.description }}</p>

        {% comment %} Tentar colocar a imagem do contato aqui no campo
        ainda não consegui fazer isso
        {% endcomment %}

        {% comment %} <p><b>Picture:</b> 
        <img src="{{ imagem.url_imagem }}" alt="{{ imagem.titulo }}"> 
        {% endcomment %}

    </div>
    {% include "contact_log/partials/_pagination.html" %}
    {% endblock content %}


</body>
</html>